package reporter

import (
	"bytes"
	"encoding/json"
	"html/template"
	"os"

	"github.com/ibrahimkizilarslan/entropy-cli/pkg/engine"
)

type ReportData struct {
	ScenarioName   string
	Hypothesis     string
	Result         engine.ScenarioResult
	Timestamp      string
	EntropyVersion string
}

const htmlTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Entropy Chaos Report - {{.ScenarioName}}</title>
    <style>
        :root {
            --primary: #6366f1;
            --success: #22c55e;
            --danger: #ef4444;
            --warning: #f59e0b;
            --bg: #0f172a;
            --card-bg: #1e293b;
            --text: #f8fafc;
        }
        body {
            font-family: 'Inter', system-ui, sans-serif;
            background-color: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 2rem;
        }
        .container {
            max-width: 1000px;
            margin: 0 auto;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 2rem;
            border-bottom: 1px solid #334155;
            padding-bottom: 1rem;
        }
        .badge {
            padding: 0.5rem 1rem;
            border-radius: 9999px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-success { background-color: var(--success); }
        .badge-danger { background-color: var(--danger); }
        
        .card {
            background-color: var(--card-bg);
            border-radius: 0.75rem;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }
        .stat-item {
            text-align: center;
        }
        .stat-value {
            font-size: 2rem;
            font-weight: bold;
            display: block;
        }
        .stat-label {
            color: #94a3b8;
            font-size: 0.875rem;
        }
        .error-msg {
            color: var(--danger);
            background: rgba(239, 68, 68, 0.1);
            padding: 1rem;
            border-radius: 0.5rem;
            border-left: 4px solid var(--danger);
        }
        footer {
            text-align: center;
            margin-top: 4rem;
            color: #64748b;
            font-size: 0.875rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div>
                <h1>🌪️ Chaos Report: {{.ScenarioName}}</h1>
                <p style="color: #94a3b8;">{{.Hypothesis}}</p>
            </div>
            <span class="badge {{if .Result.Success}}badge-success{{else}}badge-danger{{end}}">
                {{if .Result.Success}}PASSED{{else}}FAILED{{end}}
            </span>
        </div>

        <div class="stats-grid">
            <div class="card stat-item">
                <span class="stat-value">{{.Result.ExecutedSteps}}/{{.Result.TotalSteps}}</span>
                <span class="stat-label">Steps Executed</span>
            </div>
            <div class="card stat-item">
                <span class="stat-value">{{.Result.ProbesPassed}}/{{.Result.ProbesTotal}}</span>
                <span class="stat-label">Probes Passed</span>
            </div>
            <div class="card stat-item">
                <span class="stat-value">{{.Result.SteadyStatePassed}}/{{.Result.SteadyStateTotal}}</span>
                <span class="stat-label">Steady State Health</span>
            </div>
        </div>

        {{if .Result.Error}}
        <div class="card">
            <h3>Failure Details</h3>
            <div class="error-msg">
                {{.Result.Error}}
            </div>
        </div>
        {{end}}

        {{if .Result.SteadyStateError}}
        <div class="card">
            <h3>Steady State Violation</h3>
            <div class="error-msg">
                {{.Result.SteadyStateError}}
            </div>
        </div>
        {{end}}

        <footer>
            Generated by Entropy {{.EntropyVersion}} • {{.Timestamp}}
        </footer>
    </div>
</body>
</html>
`

func GenerateHTMLReport(data ReportData, filePath string) error {
	tmpl, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	return os.WriteFile(filePath, buf.Bytes(), 0644)
}

func GenerateJSONReport(data ReportData, filePath string) error {
	b, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filePath, b, 0644)
}
