site_name: Entropy CLI
site_description: A developer-first chaos engineering platform designed for local microservice environments.
site_url: https://ibrahimkizilarslan.github.io/Entropy/ # Make sure this matches your repo name when you push
repo_name: ibrahimkizilarslan/Entropy
repo_url: https://github.com/ibrahimkizilarslan/Entropy
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Usage & Scenarios:
      - Scenario DSL: scenarios.md
      - Random Chaos Engine: random-chaos.md
  - CLI Reference: cli-reference.md
