package engine

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/ibrahimkizilarslan/entropy-cli/pkg/config"
	"gopkg.in/yaml.v3"
)

type composeConfig struct {
	Services map[string]interface{} `yaml:"services"`
}

func DiscoverComposeServices(cwd string) ([]string, string, error) {
	if cwd == "" {
		cwd = "."
	}
	composeFiles := []string{"docker-compose.yml", "docker-compose.yaml", "compose.yaml"}
	var found string
	for _, f := range composeFiles {
		p := filepath.Join(cwd, f)
		if _, err := os.Stat(p); err == nil {
			found = p
			break
		}
	}
	if found == "" {
		return nil, "", fmt.Errorf("could not find docker-compose.yml in the current directory")
	}

	data, err := os.ReadFile(found)
	if err != nil {
		return nil, found, fmt.Errorf("failed to read %s: %w", filepath.Base(found), err)
	}

	var parsed composeConfig
	if err := yaml.Unmarshal(data, &parsed); err != nil {
		return nil, found, fmt.Errorf("failed to parse %s: %w", filepath.Base(found), err)
	}

	var services []string
	for k := range parsed.Services {
		services = append(services, k)
	}
	if len(services) == 0 {
		return nil, found, fmt.Errorf("no services found in %s", filepath.Base(found))
	}

	return services, found, nil
}

func GenerateDefaultChaosConfig(services []string, outPath string) error {
	d15 := 15
	cfg := config.ChaosConfig{
		Interval: 10,
		Targets:  services,
		Actions: []config.ActionSpec{
			{Name: "stop"},
			{Name: "restart"},
			{Name: "delay", LatencyMs: 300, Duration: &d15},
			{Name: "limit_cpu", CPUs: 0.2, Duration: &d15},
		},
		Safety: config.SafetyConfig{
			MaxDown:  1,
			Cooldown: 20,
			DryRun:   false,
		},
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal default config: %w", err)
	}

	header := []byte("# Auto-generated by Entropy (entropy init)\n")
	content := append(header, data...)

	return os.WriteFile(outPath, content, 0644)
}
