package engine

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDiscoverComposeServices(t *testing.T) {
	tempDir := t.TempDir()

	yamlContent := `
services:
  web:
    image: nginx
  db:
    image: postgres
`
	err := os.WriteFile(filepath.Join(tempDir, "docker-compose.yml"), []byte(yamlContent), 0644)
	if err != nil {
		t.Fatalf("Failed to write compose file: %v", err)
	}

	services, foundPath, err := DiscoverComposeServices(tempDir)
	if err != nil {
		t.Fatalf("DiscoverComposeServices failed: %v", err)
	}

	if filepath.Base(foundPath) != "docker-compose.yml" {
		t.Errorf("Expected found file 'docker-compose.yml', got '%s'", filepath.Base(foundPath))
	}

	if len(services) != 2 {
		t.Errorf("Expected 2 services, got %d", len(services))
	}

	hasWeb := false
	hasDb := false
	for _, s := range services {
		if s == "web" {
			hasWeb = true
		}
		if s == "db" {
			hasDb = true
		}
	}
	if !hasWeb || !hasDb {
		t.Errorf("Expected 'web' and 'db' services, got %v", services)
	}
}

func TestDiscoverComposeServices_NoFile(t *testing.T) {
	tempDir := t.TempDir()
	_, _, err := DiscoverComposeServices(tempDir)
	if err == nil {
		t.Error("Expected error for missing compose file, got nil")
	}
	if err.Error() != "could not find docker-compose.yml in the current directory" {
		t.Errorf("Expected specific error message, got: %v", err)
	}
}

func TestDiscoverComposeServices_InvalidYaml(t *testing.T) {
	tempDir := t.TempDir()
	err := os.WriteFile(filepath.Join(tempDir, "compose.yaml"), []byte("invalid: yaml: content:"), 0644)
	if err != nil {
		t.Fatalf("Failed to write compose file: %v", err)
	}

	_, _, err = DiscoverComposeServices(tempDir)
	if err == nil {
		t.Error("Expected error for invalid yaml, got nil")
	}
}

func TestDiscoverComposeServices_NoServices(t *testing.T) {
	tempDir := t.TempDir()
	yamlContent := `
version: "3"
networks:
  default:
`
	err := os.WriteFile(filepath.Join(tempDir, "docker-compose.yml"), []byte(yamlContent), 0644)
	if err != nil {
		t.Fatalf("Failed to write compose file: %v", err)
	}

	_, _, err = DiscoverComposeServices(tempDir)
	if err == nil {
		t.Error("Expected error for missing services block, got nil")
	}
	if err.Error() != "no services found in docker-compose.yml" {
		t.Errorf("Expected specific error message, got: %v", err)
	}
}

func TestGenerateDefaultChaosConfig(t *testing.T) {
	tempDir := t.TempDir()
	outPath := filepath.Join(tempDir, "chaos.yaml")
	services := []string{"svc1", "svc2"}

	err := GenerateDefaultChaosConfig(services, outPath)
	if err != nil {
		t.Fatalf("GenerateDefaultChaosConfig failed: %v", err)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("Failed to read generated config: %v", err)
	}
	contentStr := string(content)

	if !strings.Contains(contentStr, "# Auto-generated by Entropy (entropy init)") {
		t.Error("Expected auto-generated header comment")
	}
	if !strings.Contains(contentStr, "- svc1") || !strings.Contains(contentStr, "- svc2") {
		t.Error("Expected generated config to contain the provided targets")
	}
}
