package cli

import (
	"bufio"
	"os"
	"time"

	"github.com/ibrahimkizilarslan/entropy-cli/pkg/utils"
	"github.com/pterm/pterm"
	"github.com/spf13/cobra"
)

var logsCmd = &cobra.Command{
	Use:   "logs",
	Short: "Stream the logs generated by the background chaos engine",
	Run: func(cmd *cobra.Command, args []string) {
		state := utils.NewStateManager("")
		logPath := state.LogFile()

		f, err := os.Open(logPath)
		if err != nil {
			pterm.Error.Printf("Could not open log file: %v\n", err)
			os.Exit(1)
		}
		defer f.Close()

		pterm.Info.Printf("Streaming logs from %s\n", logPath)
		pterm.Println("Press Ctrl+C to stop.")

		reader := bufio.NewReader(f)
		for {
			line, err := reader.ReadString('\n')
			if err != nil {
				time.Sleep(500 * time.Millisecond)
				continue
			}
			pterm.Print(line)
		}
	},
}

func init() {
	rootCmd.AddCommand(logsCmd)
}

